"""
Django settings for semana11 project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^m!bgp6n6co_i0bh(s35p593h7(#rz4wl1*u@x##s3)y&(kuvf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app1',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'semana11.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'semana11.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [ BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Probanding Jazzmin

JAZZMIN_SETTINGS = {
    "site_title": "Semana 11 Admin",
    "site_brand": "Nahomi UwU",
    "site_logo": "img/user_avatar.jpg",          # logo en la esquina superior izquierda
    "login_logo": "img/login_logo.jpeg",  # logo exclusivo para la pantalla de login
    # "login_logo_dark": "img/mi_logo_login_dark.png",

    "welcome_sign": "Bienvenida, guapísima 🎀",
    "copyright": "Nahomi ❤️",
    # "user_avatar": "profile.avatar_url",     # si tu modelo User tiene avatar_url

    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "GitHub", "url": "https://github.com/nahomi2004/Jazzmin-Django", "new_window": True},
    ],

    "usermenu_links": [
        {"name": "Mi Perfil", "url": "/admin/auth/user/", "icon": "fas fa-user-circle"},
        # {"name": "Salir", "url": "admin:logout", "icon": "fas fa-sign-out-alt"},
    ],

    "icons": {
        "app1.departamento": "fas fa-building",
        "app1.instructor": "fas fa-chalkboard-teacher",
        "app1.curso": "fas fa-book-open",
        "app1.estudiante": "fas fa-user-graduate",
        "app1.inscripcion": "fas fa-clipboard-list",
        "app1.tarea": "fas fa-tasks",
        "app1.entrega": "fas fa-paper-plane",
    },

    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["app1", "app1.departamento", "app1.curso", "app1.estudiante"],

    "related_modal_active": True,
    "changeform_format": "horizontal_tabs",
    # "language_chooser": True,
}

# Personalización visual avanzada:
JAZZMIN_UI_TWEAKS = {
    "theme": "flaty",              # tema claro y fresh
    # "dark_mode_theme": "darkly",    # modo oscuro elegante
    "accent": "accent-pink",

    "compact_sidebar": True,
    "navigation_fixed": True,

    "sidebar_light": True,

    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,

    "navbar": "navbar-dark navbar-pink",
    "sidebar_nav_flat_style": True,

    "brand_colour": "navbar-pink",

    "no_navbar_border": True,
    "sidebar_nav_flat_style": True,
    "sidebar_nav_legacy_style": False,
}
